import re
from typing import List, Dict, Any, Tuple, Optional

# =========================================================
# Smart Test Case Engine v2
# Drop-in replacement for backend/app/testcase_engine.py
# Exposes:
#   - make_testcases(requirements)
#   - to_markdown_table(testcases)
# =========================================================

FINAL_HEADERS = [
    "Test_Case_ID",
    "Test_Case_Title",
    "Requirement_ID",
    "Test_Item",
    "Test_Objective",
    "Test_Steps",
    "Test_Data",
    "Expected_Result",
    "Actual_Result",
    "Pass_Fail_Status",
]

BAD_FRAGMENTS = {
    "otherwise",
    "displayed by the system",
    "the following details",
    "the following screen is displayed",
    "the user can enter his various",
    "the user may enter multiple",
    "gross total income: displayed by the system",
    "this screen is the report screen generated by the system",
}

GENERIC_STOPWORDS = {
    "the", "a", "an", "of", "for", "to", "in", "on", "by", "with", "from",
    "and", "or", "is", "are", "be", "as", "at", "into", "that", "this",
    "these", "those", "will", "shall", "must", "can", "should", "may",
    "system", "application", "user", "admin",
}

_LONG_TOKEN_RE = re.compile(r"\S{70,}")
_MULTI_SPACE_RE = re.compile(r"\s+")
_REPEAT_RE = re.compile(r"(.)\1{6,}")

# ------------------------------
# Text cleanup helpers
# ------------------------------

def clean_text(text: str) -> str:
    s = "" if text is None else str(text)
    s = s.replace("\r", " ").replace("\n", " ").replace("\t", " ")
    s = _MULTI_SPACE_RE.sub(" ", s).strip()
    s = _REPEAT_RE.sub(r"\1\1", s)
    s = _LONG_TOKEN_RE.sub("", s).strip()
    return s


def short_text(text: str, limit: int = 110) -> str:
    s = clean_text(text)
    if len(s) <= limit:
        return s
    return s[:limit].rstrip() + "..."


def sanitize_fragment(text: str) -> str:
    s = clean_text(text)
    s = s.replace("Rs \\", "Rs ")
    s = s.replace("«", "").replace("»", "")
    s = s.replace(" gross total income:", " gross total income ")
    s = _MULTI_SPACE_RE.sub(" ", s).strip(" -:;,.")
    return s


def make_testcase_id(req_index: int, tc_index: int) -> str:
    return f"TC-{req_index:03d}-{tc_index:02d}"


# ------------------------------
# Requirement parsing
# ------------------------------

def extract_req_id(req: str, index: int) -> Tuple[str, str]:
    req = sanitize_fragment(req)
    m = re.match(r"^(FR\d+|FR-\d+|REQ\d+|REQ-\d+|NFR\d+|NFR-\d+)\s*[:\-]?\s*(.*)$", req, re.IGNORECASE)
    if m:
        rid = m.group(1).upper().replace("-", "")
        txt = sanitize_fragment(m.group(2)) or req
        return rid, txt
    return f"FR{index}", req


def is_bad_requirement(text: str) -> bool:
    t = sanitize_fragment(text).lower()
    if not t:
        return True
    if len(t.split()) < 5:
        return True
    if t.endswith(":"):
        return True
    if t in BAD_FRAGMENTS:
        return True
    if re.search(r"[\\]{1,}", t):
        return True
    weak_starts = [
        r"^otherwise\b",
        r"^the following\b",
        r"^displayed by the system\b",
        r"^screen is\b",
        r"^this screen is\b",
        r"^gross total income[: ]displayed by the system\b",
        r"^lac will be deducted\b",
    ]
    return any(re.search(p, t) for p in weak_starts)


def extract_entities(text: str) -> List[str]:
    t = sanitize_fragment(text)
    tokens = re.findall(r"[A-Za-z][A-Za-z0-9_-]{2,}", t)
    out: List[str] = []
    for tok in tokens:
        tl = tok.lower()
        if tl in GENERIC_STOPWORDS:
            continue
        if tl in {"valid", "invalid", "boundary", "positive", "negative"}:
            continue
        if tl not in out:
            out.append(tl)
    return out[:6]


# ------------------------------
# Requirement intent detection
# ------------------------------

def detect_feature(text: str) -> str:
    t = text.lower()

    if any(k in t for k in ["register", "registration", "sign up", "create account"]):
        return "registration"
    if any(k in t for k in ["login", "log in", "authenticate", "authentication"]):
        return "login"
    if any(k in t for k in ["forgot password", "reset password", "recover password"]):
        return "password_recovery"

    if "vehicle" in t and any(k in t for k in ["add", "create", "register", "save"]):
        return "add_vehicle"
    if "service record" in t or ("service" in t and "record" in t):
        return "service_record"
    if any(k in t for k in ["reminder", "notification", "notify", "alert"]):
        return "reminder"

    if "dashboard" in t:
        return "dashboard"
    if "report" in t:
        return "report"
    if "search" in t:
        return "search"
    if "filter" in t:
        return "filter"
    if "sort" in t:
        return "sort"

    if any(k in t for k in ["response time", "latency", "throughput", "performance", "within 3 seconds", "within 2 seconds"]):
        return "performance"
    if any(k in t for k in ["encrypt", "token", "session", "authorization", "authentication", "hash", "secure"]):
        return "security"
    if any(k in t for k in ["responsive", "mobile-friendly", "usability", "accessible"]):
        return "usability"
    if any(k in t for k in ["uptime", "availability", "backup", "recovery", "reliability", "fault tolerance"]):
        return "reliability"

    if any(k in t for k in ["calculate", "calculation", "sum", "total", "amount", "price", "cost", "bill", "percentage", "tax", "discount", "gross", "net"]):
        return "calculation"

    if any(k in t for k in ["display", "show", "view", "screen", "page", "read-only", "modifiable"]):
        return "display"
    if any(k in t for k in ["redirect", "navigate", "open page", "open screen", "press y", "press n"]):
        return "navigation"

    return "general"


def summarize_requirement(req_text: str) -> str:
    feature = detect_feature(req_text)
    names = {
        "registration": "User Registration",
        "login": "User Login",
        "password_recovery": "Password Recovery",
        "add_vehicle": "Add Vehicle",
        "service_record": "Service Record",
        "reminder": "Reminder Notification",
        "dashboard": "Dashboard",
        "report": "Report Generation",
        "search": "Search",
        "filter": "Filter",
        "sort": "Sort",
        "performance": "Performance",
        "security": "Security",
        "usability": "Usability",
        "reliability": "Reliability",
        "calculation": "Calculation",
        "display": "Display",
        "navigation": "Navigation",
        "general": "Feature",
    }
    return names.get(feature, "Feature")


# ------------------------------
# Validation / decision / calculation detection
# ------------------------------

def detect_validations(req_text: str) -> List[Dict[str, Any]]:
    text = req_text.lower()
    rules: List[Dict[str, Any]] = []

    def add_rule(kind: str, detail: str, min_value=None, max_value=None):
        rules.append({
            "kind": kind,
            "detail": detail,
            "min": min_value,
            "max": max_value,
        })

    if re.search(r"\b(required|mandatory|cannot be blank|should not be empty|must enter)\b", text):
        add_rule("mandatory", "Mandatory field validation required")
    if "email" in text:
        add_rule("email_format", "Email format validation required")
    if "password" in text:
        m = re.search(r"(?:minimum|min)\s+(\d+)\s+(?:characters|chars)", text)
        min_len = int(m.group(1)) if m else 8
        add_rule("password_length", f"Password minimum length is {min_len}", min_value=min_len)
        if "special character" in text:
            add_rule("password_special", "Password must contain special character")
    if re.search(r"\b(unique|duplicate)\b", text):
        add_rule("unique", "Uniqueness validation required")
    if re.search(r"\b(date format|valid date|date)\b", text):
        add_rule("date", "Date validation required")
    if re.search(r"\b(number|numeric|digits|integer|amount|income|tax|price|cost|discount|salary|odometer)\b", text):
        add_rule("numeric", "Numeric validation required")

    between_match = re.search(r"between\s+(\d+)\s+and\s+(\d+)", text)
    min_match = re.search(r"(?:minimum|min|at least)\s+(\d+)", text)
    max_match = re.search(r"(?:maximum|max|at most|not exceed)\s+(\d+)", text)
    if between_match:
        add_rule("range", "Range validation required", int(between_match.group(1)), int(between_match.group(2)))
    elif min_match or max_match:
        add_rule(
            "range",
            "Boundary validation required",
            int(min_match.group(1)) if min_match else None,
            int(max_match.group(1)) if max_match else None,
        )

    return rules


def has_decision_logic(req_text: str) -> bool:
    return bool(re.search(r"\b(if|when|based on|depending on|only if|otherwise|else|after|before)\b", req_text.lower()))


def has_calculation_logic(req_text: str) -> bool:
    return bool(re.search(r"\b(calculate|sum|total|price|amount|bill|cost|percentage|tax|discount|gross|net)\b", req_text.lower()))


def has_display_logic(req_text: str) -> bool:
    return bool(re.search(r"\b(display|show|view|report|screen|page|visible|displayed|read-only|modifiable)\b", req_text.lower()))


def has_navigation_logic(req_text: str) -> bool:
    return bool(re.search(r"\b(redirect|navigate|open|move to|go to|press y|press n)\b", req_text.lower()))


def plan_scenarios(feature: str, validations: List[Dict[str, Any]], req_text: str) -> List[str]:
    scenarios: List[str] = []

    if feature == "performance":
        scenarios = ["performance", "negative", "boundary"]
    elif feature == "security":
        scenarios = ["security", "negative", "validation"]
    elif feature == "usability":
        scenarios = ["functional", "boundary"]
    elif feature == "reliability":
        scenarios = ["functional", "negative"]
    else:
        scenarios.extend(["functional", "negative"])
        if validations:
            scenarios.append("validation")
            if any(v["kind"] in {"range", "password_length"} for v in validations):
                scenarios.append("boundary")
        if has_decision_logic(req_text):
            scenarios.append("decision")
        if has_calculation_logic(req_text) or feature == "calculation":
            scenarios.append("calculation")
        if has_display_logic(req_text) or has_navigation_logic(req_text) or feature in {"report", "dashboard", "service_record", "password_recovery", "reminder"}:
            scenarios.append("workflow")

    out: List[str] = []
    for s in scenarios:
        if s not in out:
            out.append(s)
    return out


# ------------------------------
# Title / Objective / Steps / Data / Expected Result
# ------------------------------

def build_title(feature: str, scenario: str, req_text: str) -> str:
    subject = summarize_requirement(req_text)
    mapping = {
        "functional": f"Verify {subject} with valid input",
        "negative": f"Verify {subject} with invalid input",
        "validation": f"Verify validation rules for {subject}",
        "boundary": f"Verify boundary handling for {subject}",
        "workflow": f"Verify end-to-end workflow for {subject}",
        "decision": f"Verify decision logic for {subject}",
        "calculation": f"Verify calculation accuracy for {subject}",
        "security": f"Verify security control for {subject}",
        "performance": f"Verify performance requirement for {subject}",
    }
    return mapping.get(scenario, f"Verify {subject}")


def build_objective(req_text: str, scenario: str) -> str:
    subject = summarize_requirement(req_text)
    labels = {
        "functional": "Verify correct behavior under valid conditions",
        "negative": "Verify safe handling of invalid or unsupported conditions",
        "validation": "Verify field-level validation rule enforcement",
        "boundary": "Verify handling of boundary and edge-case values",
        "workflow": "Verify correct end-to-end workflow behavior",
        "decision": "Verify correct behavior for each decision branch",
        "calculation": "Verify exact calculation result using known inputs",
        "security": "Verify enforcement of the required security control",
        "performance": "Verify compliance with the required performance threshold",
    }
    return f"{labels.get(scenario, 'Verify correct behavior')} for {subject}."


def build_preconditions(feature: str) -> str:
    mapping = {
        "registration": "Registration page is accessible.",
        "login": "User account exists and login page is accessible.",
        "password_recovery": "Registered account exists and password recovery page is accessible.",
        "add_vehicle": "User is logged in and Add Vehicle page is accessible.",
        "service_record": "User is logged in and at least one vehicle already exists.",
        "reminder": "User is logged in and reminder configuration feature is accessible.",
        "dashboard": "User is logged in successfully.",
        "report": "Required input has already been submitted and report generation feature is available.",
        "search": "Searchable list page is accessible and records are available.",
        "filter": "Filter controls and records are available on the listing page.",
        "sort": "Multiple sortable records are available on the listing page.",
        "calculation": "Relevant calculation page is accessible.",
        "display": "Source page is accessible.",
        "navigation": "Source page and target page are configured in the application.",
        "performance": "Application is deployed in test environment and performance monitoring is available.",
        "security": "Security controls are enabled and protected resource exists.",
        "usability": "Application is accessible on supported devices or browsers.",
        "reliability": "Application and dependent services are running.",
        "general": "Application is accessible.",
    }
    return mapping.get(feature, "Application is accessible.")


def build_steps(feature: str, scenario: str, req_text: str) -> str:
    subject = summarize_requirement(req_text)

    custom = {
        "registration": {
            "functional": [
                "Open the registration page.",
                "Enter valid registration details.",
                "Click the Register button.",
                "Verify the account is created successfully.",
            ],
            "negative": [
                "Open the registration page.",
                "Enter invalid or duplicate registration details.",
                "Click the Register button.",
                "Verify an appropriate error message is displayed.",
            ],
            "validation": [
                "Open the registration page.",
                "Leave required fields blank or enter invalid values.",
                "Click the Register button.",
                "Verify field-level validation messages are displayed.",
            ],
            "boundary": [
                "Open the registration page.",
                "Enter boundary-case values for constrained fields.",
                "Click the Register button.",
                "Verify boundary rules are enforced correctly.",
            ],
            "workflow": [
                "Register a new user with valid details.",
                "Navigate to the login page.",
                "Log in using the newly created account.",
                "Verify the user flow continues successfully.",
            ],
            "decision": [
                "Attempt registration with a new email address.",
                "Repeat registration with an already existing email address.",
                "Verify the system follows the correct path in both cases.",
            ],
        },
        "login": {
            "functional": [
                "Open the login page.",
                "Enter valid login credentials.",
                "Click the Login button.",
                "Verify the user is redirected to the authorized landing page.",
            ],
            "negative": [
                "Open the login page.",
                "Enter invalid credentials.",
                "Click the Login button.",
                "Verify login is blocked and an error message is displayed.",
            ],
            "validation": [
                "Open the login page.",
                "Leave required fields blank or enter invalid email format.",
                "Click the Login button.",
                "Verify field-level validation messages are displayed.",
            ],
            "boundary": [
                "Open the login page.",
                "Enter boundary-case values for login fields.",
                "Click the Login button.",
                "Verify the system handles boundary values correctly.",
            ],
            "workflow": [
                "Open the login page.",
                "Authenticate using valid credentials.",
                "Open a protected page after login.",
                "Verify the session remains valid in the user flow.",
            ],
            "decision": [
                "Attempt login with an active account.",
                "Attempt login with an inactive, blocked, or invalid account.",
                "Verify the system response is correct for both paths.",
            ],
        },
        "search": {
            "functional": [
                "Open the search page.",
                "Enter a valid keyword.",
                "Run the search.",
                "Verify matching results are displayed.",
            ],
            "negative": [
                "Open the search page.",
                "Enter a keyword that has no matching result.",
                "Run the search.",
                "Verify the system shows a no-results message.",
            ],
            "validation": [
                "Open the search page.",
                "Leave the search field blank or enter invalid characters if restricted.",
                "Run the search.",
                "Verify validation or safe empty-state handling.",
            ],
            "boundary": [
                "Open the search page.",
                "Enter minimum, maximum, and very long keywords.",
                "Run the search.",
                "Verify the system handles boundary input safely.",
            ],
            "workflow": [
                "Run a valid search.",
                "Open one of the returned results.",
                "Continue the flow from the selected item.",
                "Verify the workflow remains correct end-to-end.",
            ],
        },
        "calculation": {
            "functional": [
                "Open the relevant calculation page.",
                "Enter valid numeric input values.",
                "Trigger the calculation.",
                "Verify the calculated output is displayed.",
            ],
            "negative": [
                "Open the relevant calculation page.",
                "Enter invalid or non-numeric values.",
                "Trigger the calculation.",
                "Verify the system blocks invalid processing and shows an error.",
            ],
            "validation": [
                "Open the relevant calculation page.",
                "Leave required numeric fields blank or enter wrongly formatted values.",
                "Trigger the calculation.",
                "Verify validation messages are displayed.",
            ],
            "boundary": [
                "Open the relevant calculation page.",
                "Enter boundary-case numeric values.",
                "Trigger the calculation.",
                "Verify the system handles minimum and maximum values correctly.",
            ],
            "decision": [
                "Run the calculation using data for one business-rule path.",
                "Run the calculation using data for another business-rule path.",
                "Verify the correct logic branch is applied in each case.",
            ],
            "calculation": [
                "Open the relevant calculation page.",
                "Enter known numeric input values.",
                "Trigger the calculation.",
                "Compare the displayed result with the expected computed value.",
            ],
            "workflow": [
                "Complete the calculation using valid values.",
                "Proceed to the next dependent step such as report or summary screen.",
                "Verify the generated output is available in the downstream flow.",
            ],
        },
        "display": {
            "functional": [
                "Open the source page.",
                "Perform the action that should display the target information.",
                "Verify the correct information is shown on the screen.",
            ],
            "negative": [
                "Open the source page.",
                "Attempt the action using invalid or incomplete state.",
                "Verify incorrect display is blocked or handled safely.",
            ],
            "workflow": [
                "Complete the prior step required to reach the display screen.",
                "Open the target display or report screen.",
                "Verify the expected information is visible and consistent.",
            ],
        },
        "navigation": {
            "functional": [
                "Open the source page.",
                "Perform the navigation action.",
                "Verify the correct target page is opened.",
            ],
            "negative": [
                "Open the source page.",
                "Attempt navigation using invalid or unauthorized state.",
                "Verify access is blocked or redirected correctly.",
            ],
            "decision": [
                "Perform navigation for the first available option.",
                "Perform navigation for the second available option.",
                "Verify the system follows the correct path in both cases.",
            ],
            "workflow": [
                "Start at the source page.",
                "Navigate to the target page.",
                "Continue to the next step in the flow.",
                "Verify the full workflow remains correct.",
            ],
        },
    }

    if feature in custom and scenario in custom[feature]:
        steps = custom[feature][scenario]
    else:
        steps = {
            "functional": [
                f"Open the feature related to {subject}.",
                "Enter valid input values.",
                "Perform the intended action.",
                "Observe the system response.",
            ],
            "negative": [
                f"Open the feature related to {subject}.",
                "Enter invalid or unsupported input values.",
                "Perform the intended action.",
                "Observe the error handling behavior.",
            ],
            "validation": [
                f"Open the feature related to {subject}.",
                "Leave required values blank or enter invalid format values.",
                "Perform the intended action.",
                "Observe validation messages.",
            ],
            "boundary": [
                f"Open the feature related to {subject}.",
                "Enter boundary-case values.",
                "Perform the intended action.",
                "Observe the system behavior.",
            ],
            "workflow": [
                f"Start the user flow related to {subject}.",
                "Complete the required prior step.",
                "Perform the target action.",
                "Verify the downstream result in the workflow.",
            ],
            "decision": [
                f"Execute {subject} for condition A.",
                f"Execute {subject} for condition B.",
                "Verify the correct branch is followed in both cases.",
            ],
            "calculation": [
                f"Open the feature related to {subject}.",
                "Enter known numeric values.",
                "Perform the calculation.",
                "Compare displayed output with expected output.",
            ],
            "security": [
                f"Open the feature related to {subject}.",
                "Attempt access using valid and invalid security context.",
                "Verify the security control is enforced correctly.",
            ],
            "performance": [
                f"Open the feature related to {subject}.",
                "Execute the operation under expected load.",
                "Measure the response time or throughput.",
                "Compare the observed value with the required threshold.",
            ],
        }.get(scenario, [
            f"Open the feature related to {subject}.",
            "Perform the action.",
            "Observe the result.",
        ])

    return "<br>".join([f"{i+1}. {clean_text(s)}" for i, s in enumerate(steps)])


def build_test_data(feature: str, scenario: str, validations: List[Dict[str, Any]], req_text: str) -> str:
    lower = req_text.lower()

    if feature == "registration":
        data = {
            "functional": "Name: Pranav Jadhav; Email: pranav@example.com; Password: Pranav@123",
            "negative": "Duplicate Email: pranav@example.com; Invalid Email: pranavexample.com",
            "validation": "Blank Name; Blank Email; Blank Password",
            "boundary": "Password length 7 (invalid); 8 (valid); 9 (valid)",
            "workflow": "Valid registration followed by immediate login",
            "decision": "New email vs existing email",
        }
        return data.get(scenario, "Registration test data")

    if feature == "login":
        data = {
            "functional": "Email: user@example.com; Password: Pranav@123",
            "negative": "Email: user@example.com; Password: Wrong@123",
            "validation": "Blank Email; Blank Password; Invalid Email Format",
            "boundary": "Password below minimum length and at minimum allowed length",
            "workflow": "Successful login followed by dashboard access",
            "decision": "Active account vs blocked account",
        }
        return data.get(scenario, "Login test data")

    if feature == "calculation" and "tax" in lower:
        data = {
            "functional": "Annual Income: 500000; Deductions: 150000; Residency: Resident Indian",
            "negative": "Annual Income: -1000; Deductions: abc",
            "validation": "Blank Income; Blank Deductions; Non-numeric Income",
            "boundary": "Income at slab boundary; just below slab boundary; just above slab boundary",
            "decision": "With deductions vs without deductions",
            "calculation": "Annual Income: 500000; Deductions: 150000; Expected Gross Tax and Net Tax based on business rules",
            "workflow": "Calculate tax then open generated tax report",
        }
        return data.get(scenario, "Tax calculation data")

    if feature == "search":
        data = {
            "functional": "Keyword: Honda",
            "negative": "Keyword: xyz_invalid_no_match",
            "validation": "Blank Search Input",
            "boundary": "Keyword length 1; maximum allowed length; over maximum length",
            "workflow": "Valid search followed by opening a matching result",
        }
        return data.get(scenario, "Search test data")

    generic = {
        "functional": "Valid input relevant to the requirement",
        "negative": "Invalid or unsupported input relevant to the requirement",
        "validation": "Blank mandatory field or invalid format input",
        "boundary": "Boundary values relevant to the requirement",
        "workflow": "Normal user flow data relevant to the requirement",
        "decision": "Two data combinations covering different branches",
        "calculation": "Known numeric inputs and expected output",
        "security": "Authorized and unauthorized access data",
        "performance": "Expected load values and response thresholds",
    }
    return generic.get(scenario, "Relevant test data")


def build_expected_result(feature: str, scenario: str, req_text: str) -> str:
    lower = req_text.lower()

    if feature == "registration":
        results = {
            "functional": "User account is created successfully and a success confirmation is shown.",
            "negative": "System blocks registration and shows an appropriate error message.",
            "validation": "System shows field-level validation messages for missing or invalid fields.",
            "boundary": "System accepts only valid boundary values and rejects invalid out-of-range values.",
            "workflow": "User completes registration and can proceed to the next valid step such as login.",
            "decision": "System follows the correct path for new and duplicate account scenarios.",
        }
        return results.get(scenario, "Registration behavior matches the requirement.")

    if feature == "login":
        results = {
            "functional": "User is logged in successfully and redirected to the authorized landing page.",
            "negative": "System rejects invalid credentials and no session is created.",
            "validation": "System validates missing or invalid login input before authentication.",
            "boundary": "System applies login field rules correctly at boundary values.",
            "workflow": "Authenticated session remains valid throughout the protected workflow.",
            "decision": "System applies the correct path for each account state.",
        }
        return results.get(scenario, "Login behavior matches the requirement.")

    if feature == "calculation" and "tax" in lower:
        results = {
            "functional": "System calculates tax successfully for valid income and deduction values.",
            "negative": "System rejects invalid income or deduction values and prevents incorrect tax calculation.",
            "validation": "System validates all numeric and required fields before calculation.",
            "boundary": "System applies tax rules correctly at slab and limit boundaries.",
            "decision": "System applies the correct tax rule branch for the supplied condition.",
            "calculation": "Displayed gross tax and net tax values match the expected business-rule calculation.",
            "workflow": "Calculated values are available correctly in the next dependent step such as summary or report.",
        }
        return results.get(scenario, "Tax calculation behavior matches the requirement.")

    generic = {
        "functional": "System performs the requested action successfully with valid input.",
        "negative": "System rejects invalid input and shows an appropriate error message.",
        "validation": "System validates missing or invalid input before processing.",
        "boundary": "System enforces the relevant boundary rules correctly.",
        "workflow": "System supports the complete expected workflow correctly.",
        "decision": "System executes the correct branch for each applicable condition.",
        "calculation": "System returns the exact calculated output for the supplied numeric inputs.",
        "security": "System enforces the required security control correctly.",
        "performance": "Observed performance stays within the required threshold.",
    }
    return generic.get(scenario, "Expected result should be specific and measurable.")


def priority_for(feature: str, scenario: str) -> str:
    mapping = {
        "functional": "High",
        "validation": "High",
        "boundary": "High",
        "decision": "High",
        "workflow": "High",
        "calculation": "High",
        "negative": "Medium",
        "security": "High",
        "performance": "High",
    }
    return mapping.get(scenario, "Medium")


def quality_check_testcase(row: Dict[str, Any]) -> bool:
    title = (row.get("Test_Case_Title") or "").strip().lower()
    steps = (row.get("Test_Steps") or "").strip().lower()
    expected = (row.get("Expected_Result") or "").strip().lower()
    item = (row.get("Test_Item") or "").strip()

    if not row.get("Requirement_ID"):
        return False
    if not item or len(item.split()) < 5 or len(item.split()) > 35:
        return False
    if "open relevant module" in steps or "perform action" in steps or "verify expected result" in steps:
        return False
    if "system output matches requirement" in expected:
        return False
    if not title or len(title.split()) < 4:
        return False
    if not steps or not expected:
        return False
    return True


# ------------------------------
# Public API
# ------------------------------

def make_testcases(requirements: List[str]) -> List[Dict[str, Any]]:
    testcases: List[Dict[str, Any]] = []
    valid_reqs: List[Tuple[str, str]] = []

    for req in requirements or []:
        rid, rtxt = extract_req_id(req, len(valid_reqs) + 1)
        if not is_bad_requirement(rtxt):
            valid_reqs.append((rid, rtxt))

    for req_index, (req_id, req_text) in enumerate(valid_reqs, 1):
        feature = detect_feature(req_text)
        validations = detect_validations(req_text)
        scenarios = plan_scenarios(feature, validations, req_text)

        for tc_index, scenario in enumerate(scenarios, 1):
            row = {
                "Test_Case_ID": make_testcase_id(req_index, tc_index),
                "Test_Case_Title": build_title(feature, scenario, req_text),
                "Requirement_ID": req_id,
                "Test_Item": short_text(req_text, 160),
                "Test_Objective": build_objective(req_text, scenario),
                "Test_Steps": build_steps(feature, scenario, req_text),
                "Test_Data": build_test_data(feature, scenario, validations, req_text),
                "Expected_Result": build_expected_result(feature, scenario, req_text),
                "Actual_Result": "",
                "Pass_Fail_Status": "",
            }
            if quality_check_testcase(row):
                testcases.append(row)

    return testcases


def to_markdown_table(testcases: List[Dict[str, Any]]) -> str:
    if not testcases:
        return ""

    headers = FINAL_HEADERS[:]
    lines: List[str] = []
    lines.append("| " + " | ".join(headers) + " |")
    lines.append("| " + " | ".join(["---"] * len(headers)) + " |")

    for tc in testcases:
        row = []
        for h in headers:
            v = tc.get(h, "")
            v = clean_text(str(v)).replace("|", "\\|").replace("\n", "<br>")
            row.append(v)
        lines.append("| " + " | ".join(row) + " |")

    return "\n".join(lines) + "\n"
