# Generated by Django 6.0.3 on 2026-04-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_coupon_order_coupon_used_order_discount_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Banner ka naam (e.g. Diwali Offer)', max_length=100)),
                ('image', models.ImageField(help_text='Upload banner from your computer', upload_to='banners/')),
                ('link_url', models.CharField(default='#', help_text='Click karne pe kahan jayega?', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Check to show on website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
