# Generated by Django 6.0.3 on 2026-04-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_wallet_wallettransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='KiranaHub Scanner', max_length=100)),
                ('scanner_image', models.ImageField(help_text='Admin se scanner upload karein', upload_to='scanner/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
