# Generated by Django 5.2.7 on 2026-03-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('predicted_category', models.CharField(choices=[('Sports', 'Sports'), ('Technical', 'Technical'), ('Education', 'Education'), ('Politics', 'Politics'), ('Legal', 'Legal'), ('Entertainment', 'Entertainment')], max_length=100)),
                ('keywords', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
