# Generated by Django 6.0.3 on 2026-03-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cat',
            field=models.CharField(choices=[('Rice', 'Rice & Grains'), ('Atta', 'Atta & Flours'), ('Dal', 'Dals & Pulses'), ('Kirana', 'Kirana Staples')], default='Kirana', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.TextField(default='Premium quality product.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=5.0),
        ),
    ]
