# Generated by Django 6.0.3 on 2026-03-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_cat_product_desc_alter_product_image_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.CharField(choices=[('Dairy & Eggs', 'Dairy & Eggs'), ('Staples & Grains', 'Staples & Grains'), ('Snacks & Packaged Foods', 'Snacks & Packaged Foods'), ('Beverages', 'Beverages'), ('Household Essentials', 'Household Essentials'), ('Personal Care', 'Personal Care')], default='Staples & Grains', max_length=50),
        ),
    ]
