# Generated by Django 6.0.3 on 2026-03-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rider_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(default='Premium quality product from KiranaHub.'),
        ),
    ]
