# Generated by Django 5.2.7 on 2026-03-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AddField(
            model_name='document',
            name='confidence_score',
            field=models.FloatField(default=0.0, help_text='Prediction confidence percentage'),
        ),
        migrations.AlterField(
            model_name='document',
            name='keywords',
            field=models.TextField(blank=True, help_text='Top extracted keywords from document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='predicted_category',
            field=models.CharField(choices=[('Sports', 'Sports'), ('Technology', 'Technology'), ('Education', 'Education'), ('Politics', 'Politics'), ('Legal', 'Legal'), ('Entertainment', 'Entertainment'), ('Healthcare', 'Healthcare'), ('Business', 'Business'), ('National', 'National'), ('International', 'International'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
